from __future__ import annotations

from typing import Any

from backend.contracts import API_VERSION


COMPLETION_REQUEST_EXAMPLES: dict[str, dict[str, Any]] = {
    "office": {
        "user_id": 98000,
        "anchor_item_ids": [101, 102],
        "scenario": "office",
        "season": "midseason",
        "budget": 12000,
        "include_optional_fills": True,
    },
    "date": {
        "user_id": 98000,
        "anchor_item_ids": [201],
        "scenario": "date",
        "season": "summer",
        "include_optional_fills": True,
    },
    "running": {
        "user_id": 98000,
        "anchor_item_ids": [301],
        "scenario": "running",
        "season": "summer",
        "include_optional_fills": False,
    },
    "budget_running": {
        "user_id": 98000,
        "anchor_item_ids": [301],
        "scenario": "running",
        "season": "summer",
        "budget": 4000,
        "include_optional_fills": False,
    },
}


COMPLETION_RESPONSE_EXAMPLES: dict[str, dict[str, Any]] = {
    "office": {
        "api_version": API_VERSION,
        "anchors": [
            {
                "id": 101,
                "title": "Белая рубашка прямого кроя",
                "category": "shirt",
                "subcategory": "basic_shirt",
                "role": "top",
                "gender_target": "women",
                "color_raw": "белый",
                "color_family": "white",
                "fit_raw": "regular",
                "material_raw": "хлопок",
                "style_primary": "office casual",
                "style_secondary": ["basic wardrobe"],
                "formality": "smart_casual",
                "season_tags": ["spring", "autumn"],
                "weather_tags": ["mild"],
                "occasion_tags": ["office"],
                "warmth_level": 1,
            },
            {
                "id": 102,
                "title": "Черные лоферы",
                "category": "loafers",
                "subcategory": "smart_shoes",
                "role": "shoes",
                "gender_target": "women",
                "color_raw": "черный",
                "color_family": "black",
                "fit_raw": "regular",
                "material_raw": "кожа",
                "style_primary": "office casual",
                "style_secondary": ["basic wardrobe"],
                "formality": "smart_casual",
                "season_tags": ["spring", "autumn"],
                "weather_tags": ["mild"],
                "occasion_tags": ["office"],
                "warmth_level": 1,
            },
        ],
        "covered_roles": ["shoes", "top"],
        "required_roles": ["top", "bottom", "shoes"],
        "optional_roles": ["outerwear"],
        "missing_roles": ["bottom"],
        "optional_missing_roles": ["outerwear"],
        "fill_role_order": ["bottom"],
        "optional_fill_role_order": ["outerwear"],
        "fills": {
            "bottom": [
                {
                    "product_id": 1201,
                    "source_product_id": "1201",
                    "store_key": "lime",
                    "store_name": "LIME",
                    "title": "Прямые брюки из хлопка",
                    "brand": "LIME",
                    "category": "trousers",
                    "subcategory": "tailored_trousers",
                    "role": "bottom",
                    "matched_missing_role": "bottom",
                    "gender_target": "women",
                    "current_price": 7999.0,
                    "currency": "RUB",
                    "product_url": "https://lime-shop.com/example-bottom",
                    "primary_image_url": "https://example.com/bottom.jpg",
                    "color_raw": "черный",
                    "color_family": "black",
                    "style_primary": "office casual",
                    "style_secondary": ["basic wardrobe"],
                    "formality": "smart_casual",
                    "budget_tier": "mid",
                    "season_tags": ["spring", "autumn"],
                    "weather_tags": ["mild"],
                    "occasion_tags": ["office"],
                    "scenario_tags": ["office"],
                    "warmth_level": 1,
                    "body_size_relevance": ["extended_size_range"],
                    "pairing_tags": ["top", "shoes"],
                    "avoid_pairing_tags": [],
                    "score": 8.7,
                    "match_reasons": [
                        {"code": "missing_role_match", "value": "bottom", "weight": 1.0},
                        {"code": "scenario_match", "value": "office", "weight": 2.5},
                        {"code": "formality_match", "value": "smart_casual", "weight": 1.0},
                        {"code": "within_budget", "value": 12000, "weight": 0.4},
                    ],
                }
            ]
        },
        "optional_fills": {"outerwear": []},
        "completion_state": {
            "code": "FILLS_FOUND",
            "message": "Completion fills were found for at least one missing required role.",
            "is_complete": False,
            "required_fills_found": True,
            "optional_fills_found": False,
            "missing_required_roles_without_results": [],
        },
        "scenario": "office",
        "season": "midseason",
        "season_tags": ["spring", "autumn"],
        "weather_tags": ["mild", "windy"],
        "budget": 12000,
        "budget_tiers": ["low", "lower_mid", "mid"],
        "gender_target": "women",
    },
    "date": {
        "api_version": API_VERSION,
        "anchors": [
            {
                "id": 201,
                "title": "Платье-комбинация",
                "category": "dress",
                "subcategory": "slip_dress",
                "role": "dress",
                "gender_target": "women",
                "color_raw": "черный",
                "color_family": "black",
                "fit_raw": "slim",
                "material_raw": "вискоза",
                "style_primary": "feminine casual",
                "style_secondary": ["minimal"],
                "formality": "smart_casual",
                "season_tags": ["spring", "summer"],
                "weather_tags": ["warm", "mild"],
                "occasion_tags": ["date"],
                "warmth_level": 1,
            }
        ],
        "covered_roles": ["bottom", "dress", "top"],
        "required_roles": ["top", "bottom", "shoes"],
        "optional_roles": ["outerwear", "dress"],
        "missing_roles": ["shoes"],
        "optional_missing_roles": ["outerwear"],
        "fill_role_order": ["shoes"],
        "optional_fill_role_order": ["outerwear"],
        "fills": {"shoes": []},
        "optional_fills": {"outerwear": []},
        "completion_state": {
            "code": "NO_REQUIRED_FILLS_FOUND",
            "message": "No fill candidates were found for the missing required roles.",
            "is_complete": False,
            "required_fills_found": False,
            "optional_fills_found": False,
            "missing_required_roles_without_results": ["shoes"],
        },
        "scenario": "date",
        "season": "summer",
        "season_tags": ["summer"],
        "weather_tags": ["warm"],
        "budget": None,
        "budget_tiers": [],
        "gender_target": "women",
    },
    "running": {
        "api_version": API_VERSION,
        "anchors": [
            {
                "id": 301,
                "title": "Беговой спортивный топ",
                "category": "active_top",
                "subcategory": "running_top",
                "role": "active_top",
                "gender_target": "women",
                "color_raw": "черный",
                "color_family": "black",
                "fit_raw": "slim",
                "material_raw": "полиэстер",
                "style_primary": "activewear",
                "style_secondary": ["sporty casual"],
                "formality": "sport",
                "season_tags": ["spring", "summer", "autumn"],
                "weather_tags": ["indoor", "mild"],
                "occasion_tags": ["sport", "running"],
                "warmth_level": 1,
            }
        ],
        "covered_roles": ["active_top"],
        "required_roles": ["active_top", "active_bottom", "running_shoes"],
        "optional_roles": ["outerwear"],
        "missing_roles": ["active_bottom", "running_shoes"],
        "optional_missing_roles": ["outerwear"],
        "fill_role_order": ["active_bottom", "running_shoes"],
        "optional_fill_role_order": ["outerwear"],
        "fills": {
            "active_bottom": [
                {
                    "product_id": 2201,
                    "source_product_id": "2201",
                    "store_key": "lime_sport",
                    "store_name": "LIME Sport Feed",
                    "title": "Спортивные джоггеры",
                    "brand": "LIME",
                    "category": "active_bottom",
                    "subcategory": "performance_bottom",
                    "role": "active_bottom",
                    "matched_missing_role": "active_bottom",
                    "gender_target": "women",
                    "current_price": 3999.0,
                    "currency": "RUB",
                    "product_url": "https://lime-shop.com/example-active-bottom",
                    "primary_image_url": "https://example.com/active-bottom.jpg",
                    "color_raw": "черный",
                    "color_family": "black",
                    "style_primary": "activewear",
                    "style_secondary": ["sporty casual", "activewear"],
                    "formality": "sport",
                    "budget_tier": "lower_mid",
                    "season_tags": ["spring", "summer", "autumn"],
                    "weather_tags": ["mild", "indoor"],
                    "occasion_tags": ["sport", "gym"],
                    "scenario_tags": ["gym", "outdoor_light"],
                    "warmth_level": 2,
                    "body_size_relevance": ["extended_size_range"],
                    "pairing_tags": ["active_top", "running_shoes"],
                    "avoid_pairing_tags": [],
                    "score": 8.2,
                    "match_reasons": [
                        {"code": "missing_role_match", "value": "active_bottom", "weight": 1.0},
                        {"code": "scenario_alias_match", "value": ["gym", "outdoor_light"], "weight": 1.3},
                        {"code": "sport_style_match", "value": "activewear", "weight": 1.5},
                    ],
                }
            ],
            "running_shoes": [
                {
                    "product_id": 2202,
                    "source_product_id": "2202",
                    "store_key": "lime_sport",
                    "store_name": "LIME Sport Feed",
                    "title": "Комбинированные кроссовки из замши",
                    "brand": "LIME",
                    "category": "running_shoes",
                    "subcategory": "performance_shoes",
                    "role": "running_shoes",
                    "matched_missing_role": "running_shoes",
                    "gender_target": "women",
                    "current_price": 3999.0,
                    "currency": "RUB",
                    "product_url": "https://lime-shop.com/example-running-shoes",
                    "primary_image_url": "https://example.com/running-shoes.jpg",
                    "color_raw": "белый",
                    "color_family": "white",
                    "style_primary": "activewear",
                    "style_secondary": ["sporty casual", "activewear"],
                    "formality": "sport",
                    "budget_tier": "lower_mid",
                    "season_tags": ["spring", "summer", "autumn", "winter"],
                    "weather_tags": ["warm", "mild", "cold", "indoor"],
                    "occasion_tags": ["sport", "running", "hiking_light"],
                    "scenario_tags": ["gym", "running", "outdoor_light"],
                    "warmth_level": 1,
                    "body_size_relevance": ["adult_shoe_range"],
                    "pairing_tags": ["active_top", "active_bottom"],
                    "avoid_pairing_tags": ["office_only"],
                    "score": 8.6,
                    "match_reasons": [
                        {"code": "missing_role_match", "value": "running_shoes", "weight": 1.0},
                        {"code": "scenario_match", "value": "running", "weight": 2.5},
                        {"code": "sport_style_match", "value": "activewear", "weight": 1.5},
                    ],
                }
            ],
        },
        "optional_fills": {"outerwear": []},
        "completion_state": {
            "code": "FILLS_FOUND",
            "message": "Completion fills were found for at least one missing required role.",
            "is_complete": False,
            "required_fills_found": True,
            "optional_fills_found": False,
            "missing_required_roles_without_results": [],
        },
        "scenario": "running",
        "season": "summer",
        "season_tags": ["summer"],
        "weather_tags": ["warm"],
        "budget": None,
        "budget_tiers": [],
        "gender_target": "women",
    },
    "budget_running": {
        "api_version": API_VERSION,
        "anchors": [
            {
                "id": 301,
                "title": "Беговой спортивный топ",
                "category": "active_top",
                "subcategory": "running_top",
                "role": "active_top",
                "gender_target": "women",
                "color_raw": "черный",
                "color_family": "black",
                "fit_raw": "slim",
                "material_raw": "полиэстер",
                "style_primary": "activewear",
                "style_secondary": ["sporty casual"],
                "formality": "sport",
                "season_tags": ["spring", "summer", "autumn"],
                "weather_tags": ["indoor", "mild"],
                "occasion_tags": ["sport", "running"],
                "warmth_level": 1,
            }
        ],
        "covered_roles": ["active_top"],
        "required_roles": ["active_top", "active_bottom", "running_shoes"],
        "optional_roles": ["outerwear"],
        "missing_roles": ["active_bottom", "running_shoes"],
        "optional_missing_roles": ["outerwear"],
        "fill_role_order": ["active_bottom", "running_shoes"],
        "optional_fill_role_order": ["outerwear"],
        "fills": {
            "active_bottom": [],
            "running_shoes": [
                {
                    "product_id": 2202,
                    "source_product_id": "2202",
                    "store_key": "lime_sport",
                    "store_name": "LIME Sport Feed",
                    "title": "Комбинированные кроссовки из замши",
                    "brand": "LIME",
                    "category": "running_shoes",
                    "subcategory": "performance_shoes",
                    "role": "running_shoes",
                    "matched_missing_role": "running_shoes",
                    "gender_target": "women",
                    "current_price": 3999.0,
                    "currency": "RUB",
                    "product_url": "https://lime-shop.com/example-running-shoes",
                    "primary_image_url": "https://example.com/running-shoes.jpg",
                    "color_raw": "белый",
                    "color_family": "white",
                    "style_primary": "activewear",
                    "style_secondary": ["sporty casual", "activewear"],
                    "formality": "sport",
                    "budget_tier": "lower_mid",
                    "season_tags": ["spring", "summer", "autumn", "winter"],
                    "weather_tags": ["warm", "mild", "cold", "indoor"],
                    "occasion_tags": ["sport", "running", "hiking_light"],
                    "scenario_tags": ["gym", "running", "outdoor_light"],
                    "warmth_level": 1,
                    "body_size_relevance": ["adult_shoe_range"],
                    "pairing_tags": ["active_top", "active_bottom"],
                    "avoid_pairing_tags": ["office_only"],
                    "score": 8.6,
                    "match_reasons": [
                        {"code": "missing_role_match", "value": "running_shoes", "weight": 1.0},
                        {"code": "scenario_match", "value": "running", "weight": 2.5},
                        {"code": "within_budget", "value": 4000, "weight": 0.4},
                    ],
                }
            ],
        },
        "optional_fills": {"outerwear": []},
        "completion_state": {
            "code": "FILLS_FOUND",
            "message": "Completion fills were found for at least one missing required role.",
            "is_complete": False,
            "required_fills_found": True,
            "optional_fills_found": False,
            "missing_required_roles_without_results": ["active_bottom"],
        },
        "scenario": "running",
        "season": "summer",
        "season_tags": ["summer"],
        "weather_tags": ["warm"],
        "budget": 4000,
        "budget_tiers": ["low", "lower_mid"],
        "gender_target": "women",
    },
}


ERROR_RESPONSE_EXAMPLES: dict[str, dict[str, Any]] = {
    "anchors_not_found": {
        "api_version": API_VERSION,
        "error": {
            "code": "ANCHORS_NOT_FOUND",
            "message": "Selected wardrobe items were not found.",
            "details": {
                "user_id": 98000,
                "anchor_item_ids": [9991, 9992],
                "missing_anchor_item_ids": [9991, 9992],
            },
        },
    },
    "invalid_request": {
        "api_version": API_VERSION,
        "error": {
            "code": "INVALID_REQUEST",
            "message": "Request payload validation failed.",
            "details": {
                "validation_errors": [
                    {
                        "type": "list_too_short",
                        "loc": ["body", "anchor_item_ids"],
                        "msg": "List should have at least 1 item after validation, not 0",
                    }
                ]
            },
        },
    },
}


def build_completion_examples_payload() -> dict[str, Any]:
    return {
        "api_version": API_VERSION,
        "requests": COMPLETION_REQUEST_EXAMPLES,
        "responses": COMPLETION_RESPONSE_EXAMPLES,
        "errors": ERROR_RESPONSE_EXAMPLES,
    }
