"""Controlled vocabularies for the fashion data layer."""

from .fashion import (
    BLOCKED_CURATION_KEYWORDS,
    CATEGORY_ROLE_REFERENCE,
    COMPLETION_SCENARIOS,
    STORE_DEFINITIONS,
    STORE_SOURCE_PREFERENCE,
    SUPPORTED_COMPLETION_ROLES,
)

__all__ = [
    "BLOCKED_CURATION_KEYWORDS",
    "CATEGORY_ROLE_REFERENCE",
    "COMPLETION_SCENARIOS",
    "STORE_DEFINITIONS",
    "STORE_SOURCE_PREFERENCE",
    "SUPPORTED_COMPLETION_ROLES",
]
